config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :jobs
  resources :professions
  resources :addvs
  resources :institutes
  resources :organizations
  resources :cities
  resources :provinces
  resources :degrees
  resources :dtypes
  get 'static_pages/home'
  get 'static_pages/newspaper'
  root 'static_pages#home'
  get 'static_pages/help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/addv.rb
class Addv < ApplicationRecord
  belongs_to :organization
  mount_uploader :image, ImageUploader
def self.search(search)
  # Title is for the above case, the OP incorrectly had 'name'
  where("title LIKE ?", "%#{search}%")
end  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :province
end

app/models/degree.rb
class Degree < ApplicationRecord
  belongs_to :dtype
end

app/models/dtype.rb
class Dtype < ApplicationRecord
end

app/models/institute.rb
class Institute < ApplicationRecord
  belongs_to :city
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :addv
  belongs_to :profession
  belongs_to :degree
  belongs_to :city

  def self.search(search)
  # Title is for the above case, the OP incorrectly had 'name'
  where("title LIKE ?", "%#{search}%")
end
end

app/models/organization.rb
class Organization < ApplicationRecord
 has_many :addv
end

app/models/profession.rb
class Profession < ApplicationRecord
end

app/models/province.rb
class Province < ApplicationRecord
has_many :city
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/addvs_controller.rb
class AddvsController < ApplicationController
  before_action :set_addv, only: [:show, :edit, :update, :destroy]

  # GET /addvs
  # GET /addvs.json
  def index
    @addvs = Addv.all
    if params[:search]
      @addvs = Addv.search(params[:search]).order("created_at DESC")
    else
      @addvs = Addv.all.order('created_at DESC')
    end


  end

  # GET /addvs/1
  # GET /addvs/1.json
  def show
    

  end

  # GET /addvs/new
  def new
    @addv = Addv.new
  end

  # GET /addvs/1/edit
  def edit
  end

  # POST /addvs
  # POST /addvs.json
  def create
    @addv = Addv.new(addv_params)

    respond_to do |format|
      if @addv.save
        format.html { redirect_to @addv, notice: 'Addv was successfully created.' }
        format.json { render :show, status: :created, location: @addv }
      else
        format.html { render :new }
        format.json { render json: @addv.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addvs/1
  # PATCH/PUT /addvs/1.json
  def update
    respond_to do |format|
      if @addv.update(addv_params)
        format.html { redirect_to @addv, notice: 'Addv was successfully updated.' }
        format.json { render :show, status: :ok, location: @addv }
      else
        format.html { render :edit }
        format.json { render json: @addv.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addvs/1
  # DELETE /addvs/1.json
  def destroy
    @addv.destroy
    respond_to do |format|
      format.html { redirect_to addvs_url, notice: 'Addv was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_addv
      @addv = Addv.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def addv_params
      params.require(:addv).permit(:title, :image, :organization_id)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:addv_id, :profession_id, :degree_id, :city_id, :qty)
    end
end

app/helpers/addvs_helper.rb
module AddvsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/helpers/dtypes_helper.rb
module DtypesHelper
end

app/helpers/institutes_helper.rb
module InstitutesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/professions_helper.rb
module ProfessionsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/addvs/_form.html.erb
<%= form_for(addv) do |f| %>
  <% if addv.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(addv.errors.count, "error") %> prohibited this addv from being saved:</h2>

      <ul>
      <% addv.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>   
  </div>

  <div class="field">
    <%= f.label :organization_id %>
    <%= f.collection_select :organization_id, Organization.order(:name),:id,:name,include_blank: true%>
    
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addvs/edit.html.erb
<h1>Editing Addv</h1>

<%= render 'form', addv: @addv %>

<%= link_to 'Show', @addv , class: "btn btn-primary"%> |
<%= link_to 'Back', addvs_path , class: "btn btn-primary"%>

app/views/addvs/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag(addvs_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Title" %>
  <%= submit_tag "Search" %>
<% end %>

<h1>Addvs</h1>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Add Date</th>
      <th>Title</th>
      <th>Organization</th>
      <th>Image</th>

      

    </tr>
  </thead>

  <tbody>
    <% @addvs.each do |addv| %>
      <tr>
        <td><%= addv.created_at.strftime("%d-%B-%Y") %></td>
        <td><%= addv.title %></td>        
        <td><%=addv.organization.name %></td>
        <td><%= link_to "View Add", addv.image_url %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/addvs/new.html.erb
<h1>New Addv</h1>

<%= render 'form', addv: @addv %>

<%= link_to 'Back', addvs_path %>

app/views/addvs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @addv.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= @addv.image %>
</p>
<%= image_tag addv.image_url(:thumb) if addv.image? %>

<p>
  <strong>Organization:</strong>
  <%= @addv.organization %>
</p>

<%= link_to 'Edit', edit_addv_path(@addv) %> |
<%= link_to 'Back', addvs_path %>

app/views/jobs/_form.html.erb
<%= form_for(job) do |f| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :addv_id %>
    <%= f.collection_select :addv_id, Addv.order(:title),:id,:title,include_blank: true%>
  </div>

  <div class="field">
    <%= f.label :profession_id %>
    <%= f.collection_select :profession_id, Profession.order(:name),:id,:name,include_blank: true%>
  </div>

  <div class="field">
    <%= f.label :degree_id %>
    <%= f.collection_select :degree_id, Degree.order(:name),:id,:name,include_blank: true%>
  </div>

  <div class="field">
    <%= f.label :city_id %>
    <%= f.collection_select :city_id, City.order(:name),:id,:name,include_blank: true%>
  </div>

  <div class="field">
    <%= f.label :qty %>
    <%= f.number_field :qty %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>
<%= form_tag(jobs_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Job" %>
  <%= submit_tag "Search" %>
<% end %>

<h1>Jobs</h1>

<table class="table table-bordered table-striped">

  <thead>
    <tr>
      <th>Addv</th>
      <th>Profession</th>
      <th>Degree</th>
      <th>City</th>
      <th>Jobs Qty</th>
      

    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>

      <tr>
        <td><%= job.addv.title %></td>
        <td><%= job.profession.name %></td>
        <td><%= job.degree.name %></td>
        <td><%= job.city.name %></td>
        <td><%= job.qty %></td>
        

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Addv:</strong>
  <%= @job.addv %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @job.profession %>
</p>

<p>
  <strong>Degree:</strong>
  <%= @job.degree %>
</p>

<p>
  <strong>City:</strong>
  <%= @job.city %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @job.qty %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>