config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :jobs
  resources :professions
  resources :addvs
  resources :institutes
  resources :organizations
  resources :cities
  resources :provinces
  resources :degrees
  resources :dtypes
  get 'static_pages/home'
  get 'static_pages/newspaper'
  root 'static_pages#home'
  get 'static_pages/help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/addv.rb
class Addv < ApplicationRecord
  belongs_to :organization
  mount_uploader :image, ImageUploader
def self.search(search)
  # Title is for the above case, the OP incorrectly had 'name'
  where("title LIKE ?", "%#{search}%")
end  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :province
end

app/models/degree.rb
class Degree < ApplicationRecord
  belongs_to :dtype
end

app/models/dtype.rb
class Dtype < ApplicationRecord
end

app/models/institute.rb
class Institute < ApplicationRecord
  belongs_to :city
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :addv
  belongs_to :profession
  belongs_to :degree
  belongs_to :city

  def self.search(search)
  # Title is for the above case, the OP incorrectly had 'name'
  where("title LIKE ?", "%#{search}%")
end
end

app/models/organization.rb
class Organization < ApplicationRecord
 has_many :addv
end

app/models/profession.rb
class Profession < ApplicationRecord
end

app/models/province.rb
class Province < ApplicationRecord
has_many :city
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/degrees_controller.rb
class DegreesController < ApplicationController
  before_action :set_degree, only: [:show, :edit, :update, :destroy]

  # GET /degrees
  # GET /degrees.json
  def index
    @degrees = Degree.all
  end

  # GET /degrees/1
  # GET /degrees/1.json
  def show
  end

  # GET /degrees/new
  def new
    @degree = Degree.new
  end

  # GET /degrees/1/edit
  def edit
  end

  # POST /degrees
  # POST /degrees.json
  def create
    @degree = Degree.new(degree_params)

    respond_to do |format|
      if @degree.save
        format.html { redirect_to @degree, notice: 'Degree was successfully created.' }
        format.json { render :show, status: :created, location: @degree }
      else
        format.html { render :new }
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /degrees/1
  # PATCH/PUT /degrees/1.json
  def update
    respond_to do |format|
      if @degree.update(degree_params)
        format.html { redirect_to @degree, notice: 'Degree was successfully updated.' }
        format.json { render :show, status: :ok, location: @degree }
      else
        format.html { render :edit }
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /degrees/1
  # DELETE /degrees/1.json
  def destroy
    @degree.destroy
    respond_to do |format|
      format.html { redirect_to degrees_url, notice: 'Degree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_degree
      @degree = Degree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def degree_params
      params.require(:degree).permit(:dtype_id, :name)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:addv_id, :profession_id, :degree_id, :city_id, :qty)
    end
end

app/helpers/addvs_helper.rb
module AddvsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/helpers/dtypes_helper.rb
module DtypesHelper
end

app/helpers/institutes_helper.rb
module InstitutesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/professions_helper.rb
module ProfessionsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/degrees/_form.html.erb
<%= form_for(degree) do |f| %>
  <% if degree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(degree.errors.count, "error") %> prohibited this degree from being saved:</h2>

      <ul>
      <% degree.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dtype_id %>
    <%= f.collection_select :dtype_id, Dtype.order(:name),:id,:name,include_blank: true%>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/degrees/edit.html.erb
<h1>Editing Degree</h1>

<%= render 'form', degree: @degree %>

<%= link_to 'Show', @degree %> |
<%= link_to 'Back', degrees_path %>

app/views/degrees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Degrees</h1>

<table>
  <thead>
    <tr>
      <th>Dtype</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @degrees.each do |degree| %>
      <tr>
        <td><%= degree.dtype.name %></td>
        <td><%= degree.name %></td>
        <td><%= link_to 'Show', degree %></td>
        <td><%= link_to 'Edit', edit_degree_path(degree) %></td>
        <td><%= link_to 'Destroy', degree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Degree', new_degree_path %>

app/views/degrees/new.html.erb
<h1>New Degree</h1>

<%= render 'form', degree: @degree %>

<%= link_to 'Back', degrees_path %>

app/views/degrees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dtype:</strong>
  <%= @degree.dtype %>
</p>

<p>
  <strong>Name:</strong>
  <%= @degree.name %>
</p>

<%= link_to 'Edit', edit_degree_path(@degree) %> |
<%= link_to 'Back', degrees_path %>