config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :jobs
  resources :professions
  resources :addvs
  resources :institutes
  resources :organizations
  resources :cities
  resources :provinces
  resources :degrees
  resources :dtypes
  get 'static_pages/home'
  get 'static_pages/newspaper'
  root 'static_pages#home'
  get 'static_pages/help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/addv.rb
class Addv < ApplicationRecord
  belongs_to :organization
  mount_uploader :image, ImageUploader
def self.search(search)
  # Title is for the above case, the OP incorrectly had 'name'
  where("title LIKE ?", "%#{search}%")
end  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :province
end

app/models/degree.rb
class Degree < ApplicationRecord
  belongs_to :dtype
end

app/models/dtype.rb
class Dtype < ApplicationRecord
end

app/models/institute.rb
class Institute < ApplicationRecord
  belongs_to :city
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :addv
  belongs_to :profession
  belongs_to :degree
  belongs_to :city

  def self.search(search)
  # Title is for the above case, the OP incorrectly had 'name'
  where("title LIKE ?", "%#{search}%")
end
end

app/models/organization.rb
class Organization < ApplicationRecord
 has_many :addv
end

app/models/profession.rb
class Profession < ApplicationRecord
end

app/models/province.rb
class Province < ApplicationRecord
has_many :city
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/dtypes_controller.rb
class DtypesController < ApplicationController
  before_action :set_dtype, only: [:show, :edit, :update, :destroy]

  # GET /dtypes
  # GET /dtypes.json
  def index
    @dtypes = Dtype.all
  end

  # GET /dtypes/1
  # GET /dtypes/1.json
  def show
  end

  # GET /dtypes/new
  def new
    @dtype = Dtype.new
  end

  # GET /dtypes/1/edit
  def edit
  end

  # POST /dtypes
  # POST /dtypes.json
  def create
    @dtype = Dtype.new(dtype_params)

    respond_to do |format|
      if @dtype.save
        format.html { redirect_to @dtype, notice: 'Dtype was successfully created.' }
        format.json { render :show, status: :created, location: @dtype }
      else
        format.html { render :new }
        format.json { render json: @dtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dtypes/1
  # PATCH/PUT /dtypes/1.json
  def update
    respond_to do |format|
      if @dtype.update(dtype_params)
        format.html { redirect_to @dtype, notice: 'Dtype was successfully updated.' }
        format.json { render :show, status: :ok, location: @dtype }
      else
        format.html { render :edit }
        format.json { render json: @dtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dtypes/1
  # DELETE /dtypes/1.json
  def destroy
    @dtype.destroy
    respond_to do |format|
      format.html { redirect_to dtypes_url, notice: 'Dtype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dtype
      @dtype = Dtype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dtype_params
      params.require(:dtype).permit(:name, :remarks)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:addv_id, :profession_id, :degree_id, :city_id, :qty)
    end
end

app/helpers/addvs_helper.rb
module AddvsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/helpers/dtypes_helper.rb
module DtypesHelper
end

app/helpers/institutes_helper.rb
module InstitutesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/professions_helper.rb
module ProfessionsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/dtypes/_form.html.erb
<%= form_for(dtype) do |f| %>
  <% if dtype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dtype.errors.count, "error") %> prohibited this dtype from being saved:</h2>

      <ul>
      <% dtype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :remarks %>
    <%= f.text_field :remarks %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dtypes/edit.html.erb
<h1>Editing Dtype</h1>

<%= render 'form', dtype: @dtype %>

<%= link_to 'Show', @dtype %> |
<%= link_to 'Back', dtypes_path %>

app/views/dtypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dtypes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Remarks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dtypes.each do |dtype| %>
      <tr>
        <td><%= dtype.name %></td>
        <td><%= dtype.remarks %></td>
        <td><%= link_to 'Show', dtype %></td>
        <td><%= link_to 'Edit', edit_dtype_path(dtype) %></td>
        <td><%= link_to 'Destroy', dtype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dtype', new_dtype_path %>

app/views/dtypes/new.html.erb
<h1>New Dtype</h1>

<%= render 'form', dtype: @dtype %>

<%= link_to 'Back', dtypes_path %>

app/views/dtypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dtype.name %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @dtype.remarks %>
</p>

<%= link_to 'Edit', edit_dtype_path(@dtype) %> |
<%= link_to 'Back', dtypes_path %>